[package]
name = "kernel"
version = "2.0.0"
edition = "2018"

[lib]
name = "kernel"
crate-type = ["staticlib"]

[features]
default = []
testing = []

[dependencies]
spin = "0.5.2"
syscall = {path = "../syscall"}

[build-dependencies]
cc = "1.0.50"
