pub const REGION_TYPE_FREE: u32 = 1;
pub const REGION_TYPE_RESERVED: u32 = 2;

/**
 * Structure for handling the data generated by the BIOS memory mapping call
 * (INT 0x15, EAX = 0xE820). The method generates a map somewhere in memory
 * where each 24-bit entry identifies a region of memory.
 */
#[repr(C, packed)]
pub struct MapEntry {
  pub base: u64,
  pub length: u64,
  pub region_type: u32,
  pub acpi: u32,
}

pub unsafe fn load_entries_at_address(addr: usize) -> &'static [MapEntry] {
  let length = addr as *const usize;
  let first_entry = (addr as *mut u32).offset(1) as *mut MapEntry;
  core::slice::from_raw_parts_mut(first_entry, *length)
}
